project_id = "iartslbielcqmuhygzku"

[functions.asaas-payment]
verify_jwt = false

[functions.mapbox]
verify_jwt = false

[functions.create-establishment]
verify_jwt = false

[functions.delete-user]
verify_jwt = false